source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'flok_Example', :exclusive => true do
  pod "flok", :path => "../"
end

target 'flok_Tests', :exclusive => true do
  pod "flok", :path => "../"

  pod 'Quick', '~> 0.7.0'
  pod 'Nimble', '~> 2.0.0'
end
