DEBUG:
  debug_attach: socket_io
  mods:
    - ui
    - event
    - net
    - segue
    - controller
    - debug
    - sockio
    - persist
    - timer
  defines:
    - spec_test
RELEASE:
  mods:
    - ui
    - event
    - net
    - segue
    - controller
    - sockio
    - persist
    - timer
