require 'fileutils'
require 'flok/build'
require 'securerandom'
require 'tmpdir'
require 'phantomjs'
require 'tempfile'

#Compile all the *.js files into one file
task :build do
  raise "No BUILD_PATH given" unless build_path=ENV["BUILD_PATH"]
  build_path = File.expand_path(build_path)

  my_path = File.expand_path(File.dirname(__FILE__))
  Dir.mktmpdir(SecureRandom.hex) do |dir|
    Dir.chdir dir do
      Flok.src_glob("js", "#{my_path}/src/vendor", "0src_vendor.js")
      Flok.src_glob("js", "#{my_path}/src/", "1src.js")
      Flok.src_glob("js", ".", File.join(build_path, "chrome.js"))
    end
  end
end

#Make sure it runs
task :spec do
  #Build the driver
  ENV['BUILD_PATH'] = "../../../products/chrome/drivers/"
  system('rake build')

  Dir.chdir "../../../products/chrome/drivers/" do
    #Copy chrome.js and spec files into glob folder
    FileUtils.mkdir_p "./glob"
    FileUtils.cp "chrome.js", "./glob"
    Flok.src_glob_r("js", File.join(File.dirname(__FILE__), "./spec/"), "./glob/spec.js")

    #Compile into one chrome-test.js file
    Flok.src_glob("js", "./glob/", "chrome-test.js")

    #Now run (it already includes the spec runners in the spec folder)
    system('phantomjs chrome-test.js');
  end
end

#Establish an environment with a pipe assuming the world is built
task :pipe => :build do
  raise "No BUILD_PATH given" unless build_path=ENV["BUILD_PATH"]

  exec "ruby", "-e", %{
    require './pipe'
    server = InteractiveServer.new "../../../products/chrome/drivers/chrome.js"
    server.begin_pipe
  }
end
