require 'fileutils'
require_relative '../../../lib/flok'
require 'securerandom'
require 'tmpdir'
require 'tempfile'
require 'erb'
require 'cakery'
require '../../../spec/lib/helpers.rb'

#Compile all the *.js files into one file
task :build do
  raise "No BUILD_PATH given" unless build_path=ENV["BUILD_PATH"]
  build_path = File.expand_path(build_path)

  raise "FLOK_ENV must be debug or release got #{ENV['FLOK_ENV']}" unless ["DEBUG", "RELEASE"].include? ENV["FLOK_ENV"]
end

#Make sure it runs
task :spec do
  #Build the driver
  ENV['BUILD_PATH'] = "../../../products/apple/drivers/"
  ENV['FLOK_ENV'] = 'DEBUG'
  system('rake build')

  include SpecHelpers
  $stderr.puts "Starting APPLE spec test"
  $stderr.puts "-----------------------------------------------------"
  puts "hi"
end

#Establish an environment with a pipe assuming the world is built
task :pipe => :build do
  raise "No BUILD_PATH given" unless build_path=ENV["BUILD_PATH"]

  exec "ruby", "-e", %{
  }
end
